# This is a GitHub Actions workflow file. It defines a set of automated checks
# that will run every time code is pushed to the repository.

# 1. Give the workflow a name
name: CI Checks

# 2. Define the triggers for this workflow
on: [push, pull_request]

# 3. Define the jobs to run
jobs:
  build-and-lint:
    # Use the latest version of Ubuntu as the runner environment
    runs-on: ubuntu-latest

    # Define the sequence of steps in this job
    steps:
      # Step to check out the repository's code so the workflow can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step to install our linter dependency
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # --- THIS IS THE NEW STEP ---
      # Step to install Docker Compose, which is not available by default
      - name: Install Docker Compose
        run: |
          COMPOSE_VERSION="1.29.2" # Use a specific, known-stable version
          sudo curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Step to run the linter on our Python scripts
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Step to set up Docker's modern builder, Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step to run our "compile" check: building the Docker images
      - name: Build Docker images
        run: docker-compose build
